version: '3.8'

services:
  web:
    build: ./django-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django-app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    links:
     - db:database

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
          - 5432:5432

volumes:
  postgres-data: