version: '3.8'

services:
  web:
    build:
      context: ./django-app
      dockerfile: Dockerfile.prod
    command: gunicorn django-app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/users/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    links:
     - db:database #Want to access db from extern client

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 5432:5432
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/users/static
    ports:
      - 1337:80
    depends_on:
      - web
      
volumes:
  postgres_data:
  static_volume: